# Generated by Django 3.1.12 on 2025-08-30 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConversionDjango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('input_file_id', models.CharField(max_length=255)),
                ('output_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('input_format', models.CharField(max_length=10)),
                ('output_format', models.CharField(default='mp3', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_size_input', models.BigIntegerField(blank=True, null=True)),
                ('file_size_output', models.BigIntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'video_conversions',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='VideoConversion',
        ),
    ]
